
export interface Course {
  id: string;
  name: string;
  category: string;
  description: string;
  price: number;
  image: string;
  tags: string[];
  purchaseUrl: string;
  isPopular?: boolean;
}

export const COURSES: Course[] = [
  // FORMAÇÃO
  {
    id: "mopp-formacao",
    name: "FORMAÇÃO MOPP",
    category: "Especialização (Formação)",
    description: "Movimentação de Produtos Perigosos. Essencial para motoristas que transportam cargas químicas e inflamáveis.",
    price: 319.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/mopp-formacao.jpg",
    tags: ["Mais vendido", "Oficial"],
    isPopular: true,
  },
  {
    id: "escolar-formacao",
    name: "FORMAÇÃO ESCOLAR",
    category: "Especialização (Formação)",
    description: "Capacite-se para o transporte de crianças e adolescentes com total segurança.",
    price: 319.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/escolar-formacao.jpg",
    tags: ["Mais procurado"],
    isPopular: true,
  },
  {
    id: "coletivo-formacao",
    name: "FORMAÇÃO COLETIVO PASSAGEIROS",
    category: "Especialização (Formação)",
    description: "Curso obrigatório para motoristas de ônibus e transporte coletivo.",
    price: 299.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/coletivo-formacao.jpg",
    tags: ["Essencial"],
    isPopular: true,
  },
  {
    id: "emergencia-formacao",
    name: "FORMAÇÃO EMERGÊNCIA",
    category: "Especialização (Formação)",
    description: "Treinamento especializado para condutores de veículos de socorro e emergência.",
    price: 319.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/emergencia-formacao.jpg",
    tags: ["Certificado Válido"],
  },
  {
    id: "indivisivel-formacao",
    name: "FORMAÇÃO CARGA INDIVISÍVEL",
    category: "Especialização (Formação)",
    description: "Capacitação para o transporte de cargas de grandes dimensões e pesos elevados.",
    price: 349.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/indivisivel-formacao.jpg",
    tags: ["Carga Especial"],
  },

  // ATUALIZAÇÃO
  {
    id: "mopp-atualizacao",
    name: "ATUALIZAÇÃO MOPP",
    category: "Especialização (Atualização)",
    description: "Renove seu curso de MOPP de forma rápida e 100% online.",
    price: 169.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/mopp-atualizacao.jpg",
    tags: ["Renovação"],
  },
  {
    id: "escolar-atualizacao",
    name: "ATUALIZAÇÃO ESCOLAR",
    category: "Especialização (Atualização)",
    description: "Atualize seus conhecimentos para continuar atuando no transporte escolar.",
    price: 169.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/escolar-atualizacao.jpg",
    tags: ["Renovação"],
  },
  {
    id: "coletivo-atualizacao",
    name: "ATUALIZAÇÃO COLETIVO PASSAGEIROS",
    category: "Especialização (Atualização)",
    description: "Atualização obrigatória para motoristas de ônibus e transporte de passageiros.",
    price: 159.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/coletivo-atualizacao.jpg",
    tags: ["Renovação"],
  },
  {
    id: "emergencia-atualizacao",
    name: "ATUALIZAÇÃO EMERGÊNCIA",
    category: "Especialização (Atualização)",
    description: "Renovação do curso para condutores de veículos de socorro e emergência.",
    price: 169.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/emergencia-atualizacao.jpg",
    tags: ["Renovação"],
  },
  {
    id: "indivisivel-atualizacao",
    name: "ATUALIZAÇÃO CARGA INDIVISÍVEL",
    category: "Especialização (Atualização)",
    description: "Renove sua habilitação para transporte de cargas indivisíveis.",
    price: 179.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/indivisivel-atualizacao.jpg",
    tags: ["Renovação"],
  },

  // CURSOS LIVRES
  {
    id: "curso-livre-mopp",
    name: "CURSO LIVRE ATUALIZAÇÃO MOPP",
    category: "Cursos Livres",
    description: "Conhecimento extra e atualização rápida para profissionais de produtos perigosos.",
    price: 129.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/curso-livre-mopp.jpg",
    tags: ["Conhecimento"],
  },
  {
    id: "curso-livre-escolar",
    name: "CURSO LIVRE ATUALIZAÇÃO ESCOLAR",
    category: "Cursos Livres",
    description: "Complemento educacional focado em transporte de escolares.",
    price: 129.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/curso-livre-escolar.jpg",
    tags: ["Conhecimento"],
  },
  {
    id: "curso-livre-coletivo",
    name: "CURSO LIVRE ATUALIZAÇÃO COLETIVO PASSAGEIROS",
    category: "Cursos Livres",
    description: "Aprimoramento para motoristas de transporte de passageiros.",
    price: 129.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/curso-livre-coletivo.jpg",
    tags: ["Conhecimento"],
  },
  {
    id: "curso-livre-indivisivel",
    name: "CURSO LIVRE ATUALIZAÇÃO CARGA INDIVISÍVEL",
    category: "Cursos Livres",
    description: "Atualização livre para condutores de cargas especiais.",
    price: 139.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/curso-livre-indivisivel.jpg",
    tags: ["Conhecimento"],
  },

  // TREINAMENTOS
  {
    id: "direcao-defensiva",
    name: "Direção Defensiva",
    category: "Treinamento Profissional",
    description: "Técnicas essenciais para evitar acidentes e preservar vidas no trânsito.",
    price: 89.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/direcao-defensiva.jpg",
    tags: ["Segurança"],
  },
  {
    id: "defensiva-socorros",
    name: "DIREÇÃO DEFENSIVA E PRIMEIROS SOCORROS",
    category: "Treinamento Profissional",
    description: "Combo completo unindo segurança veicular e atendimento básico de emergência.",
    price: 149.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/defensiva-socorros.jpg",
    tags: ["Combo", "Completo"],
  },
  {
    id: "direcao-economica",
    name: "Direção Econômica",
    category: "Treinamento Profissional",
    description: "Aprenda a reduzir custos com combustível e manutenção através da condução inteligente.",
    price: 99.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/direcao-economica.jpg",
    tags: ["Economia"],
  },
  {
    id: "legislacao-motorista",
    name: "Legislação Motorista Profissional",
    category: "Treinamento Profissional",
    description: "Fique por dentro das normas e leis que regem a profissão do motorista.",
    price: 79.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/legislacao-motorista.jpg",
    tags: ["Oficial"],
  },
  {
    id: "monitor-escolar",
    name: "MONITOR ESCOLAR",
    category: "Treinamento Profissional",
    description: "Qualificação específica para auxiliares e monitores de transporte escolar.",
    price: 119.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/monitor-escolar.jpg",
    tags: ["Educação"],
  },
  {
    id: "primeiros-socorros",
    name: "PRIMEIROS SOCORROS",
    category: "Treinamento Profissional",
    description: "Capacitação em suporte básico de vida para situações de trânsito.",
    price: 89.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/primeiros-socorros.jpg",
    tags: ["Saúde"],
  },
  {
    id: "observadores",
    name: "Qualificação de Observadores",
    category: "Treinamento Profissional",
    description: "Treinamento especializado para gestão e observação técnica de trânsito.",
    price: 159.90,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/observadores.jpg",
    tags: ["Especialista"],
  },

  // NRs
  {
    id: "nr-06",
    name: "NR-06",
    category: "Normas Regulamentadoras",
    description: "Treinamento sobre Equipamentos de Proteção Individual (EPI).",
    price: 129.00,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/nr-06.jpg",
    tags: ["Segurança"],
  },
  {
    id: "nr-11",
    name: "NR-11",
    category: "Normas Regulamentadoras",
    description: "Segurança no transporte, movimentação, armazenagem e manuseio de materiais.",
    price: 189.00,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/nr-11.jpg",
    tags: ["Logística"],
  },
  {
    id: "nr-16",
    name: "NR-16",
    category: "Normas Regulamentadoras",
    description: "Atividades e Operações Perigosas conforme a legislação trabalhista.",
    price: 179.00,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/nr-16.jpg",
    tags: ["Risco"],
  },
  {
    id: "nr-20",
    name: "NR-20",
    category: "Normas Regulamentadoras",
    description: "Segurança e saúde no trabalho com inflamáveis e combustíveis.",
    price: 199.00,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/nr-20.jpg",
    tags: ["Especializado"],
  },
  {
    id: "nr-35",
    name: "NR-35",
    category: "Normas Regulamentadoras",
    description: "Treinamento completo para atividades realizadas em altura.",
    price: 149.00,
    purchaseUrl: "https://pay.hotmart.com/ID_AQUI",
    image: "/image/nr-35.jpg",
    tags: ["Segurança"],
  },
];
