
export interface CourseModule {
  title: string;
  hours: string;
  description: string;
}

export interface Course {
  id: string;
  name: string;
  category: string;
  description: string;
  longDescription?: string;
  price: number;
  image: string;
  tags: string[];
  purchaseUrl: string;
  whatsappUrl: string;
  isPopular?: boolean;
  hours?: string;
  minDays?: string;
  requirements?: string[];
  modules?: CourseModule[];
}

export const COURSES: Course[] = [
  // APH - NOVO
  {
    id: "aph-formacao",
    name: "CURSO DE ATENDIMENTO PRÉ-HOSPITALAR (APH) - FORMAÇÃO",
    category: "Especialização (Formação)",
    description: "Formação essencial para quem deseja atuar no atendimento inicial a vítimas em situações de urgência e emergência.",
    longDescription: "O Curso de APH é uma formação essencial para quem deseja atuar no atendimento inicial a vítimas em situações de urgência e emergência, garantindo suporte rápido e eficiente até a chegada ao hospital. Com aulas 100% online, o curso oferece flexibilidade para estudar no seu ritmo, preparando você para agir com técnica, segurança e responsabilidade em momentos decisivos.",
    price: 190.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=2c2c4ad1-0783-42f6-92dc-6adb324b9bb8", // Usando emergência como base/placeholder
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20Atendimento%20Pr%C3%A9-Hospitalar%20(APH)%20Forma%C3%A7%C3%A3o",
    image: "/image/aph.jpg",
    tags: ["Novo", "Saúde"],
    hours: "50 horas/aula",
    minDays: "7 dias",
    requirements: [
      "Ter no mínimo 18 anos",
      "Ter interesse ou atuar na área de saúde, resgate ou atendimento emergencial",
      "Possuir disponibilidade para realizar o curso 100% online",
      "Estar ciente das exigências legais para atuação em atendimento pré-hospitalar"
    ],
    modules: [
      { title: "Módulo 1 – Direção defensiva", hours: "12h", description: "Técnicas para garantir a segurança no trânsito ao se deslocar para atendimentos emergenciais." },
      { title: "Módulo 2 – Legislação e Normas", hours: "13h", description: "Conheça detalhadamente as normas que regem o atendimento pré-hospitalar e as responsabilidades." },
      { title: "Módulo 3 – Relacionamento Interpessoal", hours: "10h", description: "Aprenda a se comunicar com clareza e empatia em situações de emergência." },
      { title: "Módulo 4 – Primeiros Socorros e Meio Ambiente", hours: "15h", description: "Procedimentos para agir em emergências e garantir o respeito no local de atendimento." }
    ]
  },
  {
    id: "aph-atualizacao",
    name: "CURSO DE ATENDIMENTO PRÉ-HOSPITALAR (APH) - ATUALIZAÇÃO",
    category: "Especialização (Atualização)",
    description: "Renove seus conhecimentos em APH para continuar atuando com excellence no suporte básico de vida.",
    price: 100.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=c603e074-b610-46d6-ae2a-f7c4f29a1b37",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pela%20atualiza%C3%A7%C3%A3o%20do%20curso%20de%20Atendimento%20Pr%C3%A9-Hospitalar%20(APH)",
    image: "/image/aph.jpg",
    tags: ["Renovação"],
    hours: "16 horas/aula",
  },
  // FORMAÇÃO
  {
    id: "mopp-formacao",
    name: "CURSO PARA CONDUTORES DE TRANSPORTE DE PRODUTOS PERIGOSOS (MOPP)",
    category: "Especialização (Formação)",
    description: "Formação essencial para motoristas que transportam cargas químicas e inflamáveis.",
    longDescription: "O curso destina-se a motoristas que desejam se profissionalizar e exercer a atividade remunerada de transporte de produtos ou resíduos perigosos. O curso de Cargas Perigosas (MOPP) é especialmente desenvolvido para capacitar todos aqueles que buscam ingressar ou aprimorar sua atuação em atividades remuneradas no transporte, visando agir com responsabilidade e segurança.",
    price: 190.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=a51412f4-114a-4274-ada6-b04b83d6e0a1",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20para%20condutores%20de%20transporte%20de%20produtos%20perigosos",
    image: "/image/mopp-formacao.jpg",
    tags: ["Mais vendido", "Oficial"],
    isPopular: true,
    hours: "50 horas/aula",
    minDays: "7 dias",
    requirements: [
      "Ser maior de 21 anos",
      "Estar habilitado em uma das categorias “B”, “C”, “D” ou “E”",
      "Possuir CNH válida (não estar suspenso ou cassado)"
    ],
    modules: [
      { title: "Legislação de Trânsito", hours: "10h", description: "CTB, sinalização, infrações e normas específicas de transporte." },
      { title: "Direção Defensiva", hours: "15h", description: "Prevenção de acidentes e comportamento seguro na condução especializada." },
      { title: "Primeiros Socorros e Meio Ambiente", hours: "10h", description: "Providências em acidentes e normas do CONAMA sobre poluição." },
      { title: "Movimentação de Produtos Perigosos", hours: "15h", description: "Classificação, simbologia e reações químicas dos produtos." }
    ]
  },
  {
    id: "escolar-formacao",
    name: "CURSO PARA CONDUTORES DE TRANSPORTE ESCOLAR",
    category: "Especialização (Formação)",
    description: "Capacite-se para o transporte de crianças e adolescentes com total segurança.",
    longDescription: "Este curso habilita o condutor a realizar o transporte de escolares conforme as exigências do CTB, focando na segurança dos passageiros e na ética profissional necessária para lidar com o público infantil.",
    price: 190.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=3760e237-5f3c-4589-9f07-846e59632c31",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20para%20condutores%20de%20transporte%20escolar",
    image: "/image/escolar-formacao.jpg",
    tags: ["Mais procurado"],
    isPopular: true,
    hours: "50 horas/aula",
    minDays: "7 dias",
    requirements: ["Ser maior de 21 anos", "Habilitado na categoria D", "CNH válida"],
    modules: [
      { title: "Legislação de Trânsito", hours: "10h", description: "Normas específicas para o transporte escolar." },
      { title: "Direção Defensiva", hours: "15h", description: "Técnicas de segurança aplicada ao transporte de pessoas." },
      { title: "Primeiros Socorros", hours: "10h", description: "Atendimento emergencial focado no público escolar." },
      { title: "Relações Interpessoais", hours: "15h", description: "Trato com alunos, pais e responsáveis." }
    ]
  },
  {
    id: "coletivo-formacao",
    name: "CURSO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE COLETIVO DE PASSAGEIROS",
    category: "Especialização (Formação)",
    description: "Curso obrigatório para motoristas de ônibus e transporte coletivo.",
    price: 190.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=1afa6922-8309-4ce2-87c2-4d7c3de29d0f",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20para%20condutores%20de%20ve%C3%ADculo%20de%20transporte%20coletivo%20de%20passageiros",
    image: "/image/coletivo-formacao.jpg",
    tags: ["Essencial"],
    hours: "50 horas/aula",
    minDays: "7 dias",
  },
  {
    id: "emergencia-formacao",
    name: "CURSO PARA CONDUTORES DE VEÍCULOS DE EMERGÊNCIA",
    category: "Especialização (Formação)",
    description: "Treinamento especializado para condutores de veículos de socorro e emergência.",
    price: 190.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=2c2c4ad1-0783-42f6-92dc-6adb324b9bb8",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20para%20condutores%20de%20ve%C3%ADculos%20de%20emerg%C3%AAncia",
    image: "/image/emergencia-formacao.jpg",
    tags: ["Certificado Válido"],
    hours: "50 horas/aula",
    minDays: "7 dias",
  },
  {
    id: "indivisivel-formacao",
    name: "CURSO PARA CONDUTORES DE TRANSPORTE CARGAS INDIVISÍVEIS",
    category: "Especialização (Formação)",
    description: "Capacitação para o transporte de cargas de grandes dimensões e pesos elevados.",
    price: 190.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=246a962b-7109-4239-bb76-f0c1cbf1652e",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20para%20condutores%20de%20transporte%20de%20cargas%20indivis%C3%ADveis",
    image: "/image/indivisivel-formacao.jpg",
    tags: ["Carga Especial"],
    hours: "50 horas/aula",
    minDays: "7 dias",
  },

  // ATUALIZAÇÃO
  {
    id: "mopp-atualizacao",
    name: "ATUALIZAÇÃO PARA CONDUTORES DE TRANSPORTE DE PRODUTOS PERIGOSOS",
    category: "Especialização (Atualização)",
    description: "Renove seu curso de MOPP de forma rápida e 100% online.",
    price: 100.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=69009ab7-c73b-431e-bd75-09e01afcf247",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pela%20atualiza%C3%A7%C3%A3o%20para%20condutores%20de%20ve%C3%ADculo%20de%20transporte%20de%20produtos%20perigosos",
    image: "/image/mopp-atualizacao.jpg",
    tags: ["Renovação"],
    hours: "16 horas/aula",
  },
  {
    id: "escolar-atualizacao",
    name: "ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE ESCOLARES",
    category: "Especialização (Atualização)",
    description: "Atualize seus conhecimentos para continuar atuando no transporte escolar.",
    price: 100.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=9aada21b-d5b0-4e99-ac0b-ba604d96ba0a",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pela%20atualiza%C3%A7%C3%A3o%20para%20condutores%20de%20ve%C3%ADculo%20de%20transporte%20de%20escolares",
    image: "/image/escolar-atualizacao.jpg",
    tags: ["Renovação"],
    hours: "16 horas/aula",
  },
  {
    id: "coletivo-atualizacao",
    name: "ATUALIZAÇÃO PARA CONDUTORES DE TRANSPORTE COLETIVO DE PASSAGEIROS",
    category: "Especialização (Atualização)",
    description: "Atualização obrigatória para motoristas de ônibus e transporte de passageiros.",
    price: 100.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=66049725-d2a0-4ded-aa61-6080018e2d8b",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pela%20atualiza%C3%A7%C3%A3o%20para%20condutores%20de%20ve%C3%ADculo%20de%20transporte%20coletivo%20de%20passageiros",
    image: "/image/coletivo-atualizacao.jpg",
    tags: ["Renovação"],
    hours: "16 horas/aula",
  },
  {
    id: "emergencia-atualizacao",
    name: "ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE EMERGÊNCIA",
    category: "Especialização (Atualização)",
    description: "Renovação do curso para condutores de veículos de socorro e emergência.",
    price: 100.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=c603e074-b610-46d6-ae2a-f7c4f29a1b37",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pela%20atualiza%C3%A7%C3%A3o%20para%20condutores%20de%20ve%C3%ADculo%20de%20transporte%20de%20emerg%C3%AAncia",
    image: "/image/emergencia-atualizacao.jpg",
    tags: ["Renovação"],
    hours: "16 horas/aula",
  },
  {
    id: "indivisivel-atualizacao",
    name: "ATUALIZAÇÃO PARA CONDUTORES DE TRANSPORTE DE CARGAS INDIVISÍVEIS",
    category: "Especialização (Atualização)",
    description: "Renove sua habilitação para transporte de cargas indivisíveis.",
    price: 100.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=803958fc-9672-4a3f-b12a-31ad36c9e980",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pela%20atualiza%C3%A7%C3%A3o%20para%20condutores%20de%20transporte%20de%20cargas%20indivis%C3%ADveis",
    image: "/image/indivisivel-atualizacao.jpg",
    tags: ["Renovação"],
    hours: "16 horas/aula",
  },

  // CURSOS LIVRES
  {
    id: "curso-livre-mopp",
    name: "CURSO LIVRE DE ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE PRODUTOS PERIGOSOS",
    category: "Cursos Livres",
    description: "Conhecimento extra e atualização rápida para profissionais de produtos perigosos.",
    price: 45.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=add43add-d230-43f5-b5fa-852954a331bc",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20livre%20de%20atualiza%C3%A7%C3%A3o%20para%20condutores%20de%20ve%C3%ADculo%20de%20transporte%20de%20produtos%20perigosos",
    image: "/image/mopp-atualizacao.jpg",
    tags: ["Conhecimento"],
  },
  {
    id: "curso-livre-escolar",
    name: "CURSO LIVRE DE ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE ESCOLARES",
    category: "Cursos Livres",
    description: "Complemento educacional focado em transporte de escolares.",
    price: 45.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=9c545b70-69de-46c6-a75d-7362823595c7",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20livre%20de%20atualiza%C3%A7%C3%A3o%20para%20condutores%20de%20ve%C3%ADculo%20de%20transporte%20de%20escolares",
    image: "/image/escolar-atualizacao.jpg",
    tags: ["Conhecimento"],
  },
  {
    id: "curso-livre-coletivo",
    name: "CURSO LIVRE DE ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE COLETIVO DE PASSAGEIROS",
    category: "Cursos Livres",
    description: "Aprimoramento para motoristas de transporte de passageiros.",
    price: 45.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=2e4b0e2a-536f-46e1-aa53-4e9d12838221",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20livre%20de%20atualiza%C3%A7%C3%A3o%20para%20condutores%20de%20ve%C3%ADculo%20de%20transporte%20coletivo%20de%20passageiros",
    image: "/image/coletivo-atualizacao.jpg",
    tags: ["Conhecimento"],
  },
  {
    id: "curso-livre-indivisivel",
    name: "CURSO LIVRE DE ATUALIZAÇÃO PARA CONDUTORES DE TRANSPORTE DE CARGAS INDIVISÍVEIS",
    category: "Cursos Livres",
    description: "Atualização livre para condutores de cargas especiais.",
    price: 45.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=9f093f83-7367-4e13-ac35-66d1d92fa93c",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20livre%20de%20atualiza%C3%A7%C3%A3o%20para%20condutores%20de%20transporte%20de%20cargas%20indivis%C3%ADveis",
    image: "/image/indivisivel-atualizacao.jpg",
    tags: ["Conhecimento"],
  },

  // TREINAMENTOS
  {
    id: "direcao-defensiva",
    name: "DIREÇÃO DEFENSIVA",
    category: "Treinamento Profissional",
    description: "Técnicas essenciais para evitar acidentes e preservar vidas no trânsito.",
    price: 65.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=8a738e4d-6986-4c2d-8899-b13c21b0140c",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20dire%C3%A7%C3%A3o%20defensiva",
    image: "/image/direcao-defensiva.jpg",
    tags: ["Segurança"],
  },
  {
    id: "defensiva-socorros",
    name: "DIREÇÃO DEFENSIVA E PRIMEIROS SOCORROS",
    category: "Treinamento Profissional",
    description: "Combo completo unindo segurança veicular e atendimento básico de emergência.",
    price: 90.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=0b12344e-7acd-4fc2-8463-7523f26d54cb",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20dire%C3%A7%C3%A3o%20defensiva%20e%20primeiros%20socorros",
    image: "/image/defensiva-socorros.jpg",
    tags: ["Combo", "Completo"],
  },
  {
    id: "direcao-economica",
    name: "DIREÇÃO ECONÔMICA E TECNOLOGIA NO TRANSPORTE",
    category: "Treinamento Profissional",
    description: "Aprenda a reduzir custos com combustível e manutenção através da condução inteligente.",
    price: 25.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=58ff32a0-5935-45b9-9e89-0e719d9069d1",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20dire%C3%A7%C3%A3o%20econ%C3%B4mica%20e%20tecnologia%20no%20transporte",
    image: "/image/direcao-economica.jpg",
    tags: ["Economia"],
  },
  {
    id: "legislacao-motorista",
    name: "LEGISLAÇÃO DE TRÂNSITO PARA MOTORISTA PROFISSIONAL",
    category: "Treinamento Profissional",
    description: "Fique por dentro das normas e leis que regem a profissão do motorista.",
    price: 120.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=45ee4992-a4f5-49ee-ac8b-9e37642d78cc",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20legisla%C3%A7%C3%A3o%20de%20tr%C3%A2nsito%20para%20motorista%20profissional",
    image: "/image/legislacao-motorista.jpg",
    tags: ["Oficial"],
  },
  {
    id: "monitor-escolar",
    name: "MONITOR ESCOLAR",
    category: "Treinamento Profissional",
    description: "Qualificação específica para auxiliares e monitores de transporte escolar.",
    price: 80.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=db1f831a-3c22-41c5-9780-8b4757927625",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20monitor%20escolar",
    image: "/image/monitor-escolar.jpg",
    tags: ["Educação"],
  },
  {
    id: "primeiros-socorros",
    name: "PRIMEIROS SOCORROS",
    category: "Treinamento Profissional",
    description: "Capacitação em suporte básico de vida para situações de trânsito.",
    price: 20.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=a2d239af-dedb-469a-844d-1c1521a11394",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20primeiros%20socorros",
    image: "/image/primeiros-socorros.jpg",
    tags: ["Saúde"],
  },
  {
    id: "observadores",
    name: "QUALIFICAÇÃO DOS OBSERVADORES CERTIFICADOS",
    category: "Treinamento Profissional",
    description: "Treinamento especializado para gestão e observação técnica de trânsito.",
    price: 1200.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=3f590299-6407-484c-b7a8-7ca5d097a0e4",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20qualifica%C3%A7%C3%A3o%20dos%20observadores%20certificados",
    image: "/image/observadores.jpg",
    tags: ["Especialista"],
  },

  // NRs
  {
    id: "nr-06",
    name: "NR-06",
    category: "Normas Regulamentadoras",
    description: "Treinamento sobre Equipamentos de Proteção Individual (EPI).",
    price: 60.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=fb749a5c-e143-42b2-bd9c-4fd3179062df",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20NR-06",
    image: "/image/nr-06.jpg",
    tags: ["Segurança"],
  },
  {
    id: "nr-11",
    name: "NR-11 TRANSPORTE, MOVIMENTAÇÃO, ARMAZENAGEM E MANUSEIO DE MATERIAIS",
    category: "Normas Regulamentadoras",
    description: "Segurança no transporte, movimentação, armazenagem e manuseio de materiais.",
    price: 60.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=023d3d50-08bf-494c-b097-4123f7114a70",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20NR-11%20transporte%2C%20movimenta%C3%A7%C3%A3o%2C%20armazenagem%20e%20manuseio%20de%20materiais",
    image: "/image/nr-11.jpg",
    tags: ["Logística"],
  },
  {
    id: "nr-16",
    name: "NR-16 ATIVIDADES E OPERAÇÕES PERIGOSAS",
    category: "Normas Regulamentadoras",
    description: "Atividades e Operações Perigosas conforme a legislação trabalhista.",
    price: 60.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=935671c2-a46c-4bb8-812f-de8cebc3a32a",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20NR-16%20atividades%20e%20opera%C3%A7%C3%B5es%20perigosas",
    image: "/image/nr-16.jpg",
    tags: ["Risco"],
  },
  {
    id: "nr-20",
    name: "NR-20 SEGURANÇA E SAÚDE NO TRABALHO COM INFLAMÁVEIS E COMBUSTÍVEIS",
    category: "Normas Regulamentadoras",
    description: "Segurança e saúde no trabalho com inflamáveis e combustíveis.",
    price: 60.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=1e1248e2-b458-4410-9c76-3036fb77b071",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20NR-20%20seguran%C3%A7a%20e%20sa%C3%BAde%20no%20trabalho%20com%20inflam%C3%A1veis%20e%20combust%C3%ADveis",
    image: "/image/nr-20.jpg",
    tags: ["Especializado"],
  },
  {
    id: "nr-35",
    name: "NR-35 - TRABALHO EM ALTURA",
    category: "Normas Regulamentadoras",
    description: "Treinamento completo para atividades realizadas em altura.",
    price: 80.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=e4f19587-9e86-481d-86e8-ce0d5ea976d9",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20NR-35%20trabalho%20em%20altura",
    image: "/image/nr-35.jpg",
    tags: ["Segurança"],
  },

  // OUTROS
  {
    id: "reciclagem-pe",
    name: "RECICLAGEM PARA CONDUTORES INFRATORES - PE",
    category: "Reciclagem e Outros",
    description: "Curso de reciclagem oficial para condutores do estado de Pernambuco.",
    price: 250.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=8597caae-640f-4174-9831-0ef9edf124ca",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20reciclagem%20para%20condutores%20infratores",
    image: "/image/reciclagem.jpg",
    tags: ["Oficial"],
  },
  {
    id: "taxista",
    name: "TAXISTA",
    category: "Reciclagem e Outros",
    description: "Curso de capacitação profissional para condutores de Táxi.",
    price: 190.00,
    purchaseUrl: "https://ead-checkout.bludata.net/?p=b57a37c9-2eaa-46e6-a1d4-1d261e4b6527",
    whatsappUrl: "https://wa.me/5513991932590?text=Oie%2C%20tudo%20bem%3F%20Vim%20pelo%20curso%20de%20taxista",
    image: "/image/taxista.jpg",
    tags: ["Profissional"],
  },
];
